// lib/pipeline/alert-sweeper.js — Auto-resolve stale, now-healthy alerts.
//
// pipeline_alerts is append-only by default — alerts pile up forever unless
// something resolves them. The sweeper runs daily and clears alerts that
// satisfy BOTH:
//   1. age >= MIN_AGE_DAYS (default 30 days), AND
//   2. a per-type "now healthy" predicate confirms the underlying problem
//      is no longer in effect.
//
// The dual requirement (age AND health) is intentional — we never auto-
// resolve on age alone. If a real signal is buried 30 days deep, we'd
// rather wake the operator than silence it.

const MIN_AGE_DAYS_DEFAULT = 30;
const SCAN_LIMIT = 500;

// Per-event-type predicates. Each takes (supabase, alert) and returns
// Promise<boolean> — true means "now healthy, safe to resolve."
//
// Default predicate (when no entry exists for an event_type) is to leave
// the alert unresolved. Better to noisily under-sweep than silently miss
// a real signal.
const HEALTH_PREDICATES = {
  // House returned 0 lots in a scrape — confirm there are now fresh lots
  // for that house in the last 24h before resolving.
  async house_returned_zero_lots(supabase, alert) {
    if (!alert.house) return false;
    const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
    const { count, error } = await supabase
      .from('lots')
      .select('id', { count: 'exact', head: true })
      .eq('house', alert.house)
      .gte('last_seen_at', since);
    if (error) return false;
    return (count || 0) > 0;
  },

  // Same predicate as above — generated by an older event_type variant.
  async zero_lots_after_scrape(supabase, alert) {
    return HEALTH_PREDICATES.house_returned_zero_lots(supabase, alert);
  },

  // Firecrawl JSON extract returned 0 / few — confirm fresh lots exist now.
  async firecrawl_extract_regression(supabase, alert) {
    return HEALTH_PREDICATES.house_returned_zero_lots(supabase, alert);
  },

  // Legacy DOM-extractor regression — same recovery condition (lots present).
  async extractor_regression(supabase, alert) {
    return HEALTH_PREDICATES.house_returned_zero_lots(supabase, alert);
  },

  // Image coverage drop — confirm coverage has recovered.
  async image_coverage_drop(supabase, alert) {
    if (!alert.house) return false;
    const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
    const { data, error } = await supabase
      .from('lots')
      .select('image_url')
      .eq('house', alert.house)
      .gte('last_seen_at', since)
      .limit(200);
    if (error || !data || data.length === 0) return false;
    const withImg = data.filter(r => r.image_url).length;
    return (withImg / data.length) >= 0.7;
  },

  // Firecrawl budget threshold (80/95/100). Once month ticks over the local
  // counter resets and the alert is irrelevant; any single calendar-month-
  // old budget alert is safe to resolve.
  async firecrawl_budget_threshold(supabase, alert) {
    const ageMs = Date.now() - new Date(alert.created_at).getTime();
    return ageMs > 30 * 24 * 60 * 60 * 1000;
  },

  // HMLR loader failure — next month's run either succeeds (and would fire a
  // fresh alert on failure) or fails again. 30-day-old failures are safe to
  // sweep; the recurrence guard is "if it fires again, a new row appears".
  async hmlr_refresh_failed(supabase, alert) {
    const ageMs = Date.now() - new Date(alert.created_at).getTime();
    return ageMs > 30 * 24 * 60 * 60 * 1000;
  },

  // Generic recall diagnostics — same logic as zero-lots.
  async recall_diagnostic(supabase, alert) {
    return HEALTH_PREDICATES.house_returned_zero_lots(supabase, alert);
  },

  // Genuine empty calendars (e.g. between auction cycles) self-clear once
  // the next catalogue lands.
  async genuine_zero(supabase, alert) {
    return HEALTH_PREDICATES.house_returned_zero_lots(supabase, alert);
  },
};

/**
 * Sweep stale, now-healthy alerts.
 *
 * @param {object} supabase - Supabase client
 * @param {object} [opts]
 * @param {number} [opts.minAgeDays=30]
 * @param {number} [opts.scanLimit=500]
 * @returns {Promise<{ scanned: number, resolved: Array<{id, event_type, house, predicate}>, skippedNoPredicate: number, skippedNotHealthy: number }>}
 */
export async function sweepStaleAlerts(supabase, opts = {}) {
  const minAgeDays = opts.minAgeDays || MIN_AGE_DAYS_DEFAULT;
  const scanLimit = opts.scanLimit || SCAN_LIMIT;
  const cutoff = new Date(Date.now() - minAgeDays * 24 * 60 * 60 * 1000).toISOString();

  const { data: candidates, error } = await supabase
    .from('pipeline_alerts')
    .select('id, event_type, house, message, created_at, meta')
    .eq('resolved', false)
    .lte('created_at', cutoff)
    .order('created_at', { ascending: true })
    .limit(scanLimit);

  if (error) {
    return { scanned: 0, resolved: [], skippedNoPredicate: 0, skippedNotHealthy: 0, error: error.message };
  }

  const resolved = [];
  let skippedNoPredicate = 0;
  let skippedNotHealthy = 0;

  for (const alert of candidates || []) {
    const predicate = HEALTH_PREDICATES[alert.event_type];
    if (!predicate) {
      skippedNoPredicate++;
      continue;
    }
    let healthy = false;
    try { healthy = await predicate(supabase, alert); }
    catch (e) {
      console.warn(`alert-sweeper: predicate ${alert.event_type} threw —`, e?.message || e);
      healthy = false;
    }
    if (!healthy) {
      skippedNotHealthy++;
      continue;
    }

    const { error: updateErr } = await supabase
      .from('pipeline_alerts')
      .update({ resolved: true, resolved_at: new Date().toISOString() })
      .eq('id', alert.id)
      .eq('resolved', false);
    if (updateErr) {
      console.warn(`alert-sweeper: failed to resolve ${alert.id}:`, updateErr.message);
      continue;
    }
    resolved.push({ id: alert.id, event_type: alert.event_type, house: alert.house, predicate: alert.event_type });
    console.info(`alert-sweeper: resolved ${alert.id} (${alert.event_type}, house=${alert.house || '_system'}) — predicate confirmed healthy`);
  }

  return {
    scanned: candidates?.length || 0,
    resolved,
    skippedNoPredicate,
    skippedNotHealthy,
  };
}

// Export the predicate map for tests (and for any future hand-driven sweep).
export { HEALTH_PREDICATES };
